### PR TITLE
[limit] add limit utility class

### PR DESCRIPTION
**Pull request by smagnaniuni**

### CODE REVIEW

**Review by aleemont1 — APPROVED** [review]
LGTM

**Comment by michelececcacci** [comment]
LGTM.

**Comment by aleemont1** [comment]
I think it'd be better for it to treat [Numbers] (https://www.cs.usfca.edu/~cs272/javadoc/api/java.base/java/lang/Number.html) and not just integers.

**Comment by smagnaniuni** [comment]
Unfortunately Number is not comparable, so even avoiding the use of Math.min/max would not be possible, individual types should be used (can be overloaded)

**Pull request merged**
