### PR TITLE
[README] Drop contact section

### PR DESCRIPTION
**Pull request by aleemont1**

### CODE REVIEW

**Comment by michelececcacci** [comment]
LGTM

**Comment by aleemont1** [comment]
> LGTM

I'm waiting for the warning to be suppressed in #8, then we'll merge this ok?

**Comment by michelececcacci** [comment]
ok

**Comment by smagnaniuni** [comment]
The warnings will be suppressed separately from #8.

**Comment by aleemont1** [comment]
> The warnings will be suppressed separately from #8.

Whatever, i don't think it will cause any problems

**Comment by michelececcacci** [comment]
are we merging this?

**Pull request merged**
