### PR TITLE
Implement Home Environment

### LINKED ISSUE #19: Implement Home Environment
The home environment represents the "physical" environment in which the controller and the devices are running.
It will have to track physical quantities such as temperature, and air quality parameters.

### PR DESCRIPTION
**Pull request by smagnaniuni**
Closes #19 

@michelececcacci I am thinking of implementing another interface for a device whose location in the environment matters.

```java
public interface EnvironmentObject {
  void move(Environment environment);
}
```
We would also need to specify in the constructor the environment? So the device knows where it is and can call the environment methods.

Maybe also the environment needs to keep a reference of the devices in it? But that would probably lead to problems.

### CODE REVIEW

**Comment by michelececcacci** [comment]
> @michelececcacci I am thinking of implementing another interface for a device whose location in the environment matters.
I like it.
I also like the PR

**Comment by aleemont1** [comment]
> Closes #19 
> 
> @michelececcacci I am thinking of implementing another interface for a device whose location in the environment matters.
> 
> ```java
> public interface EnvironmentObject {
>   void move(Environment environment);
> }
> ```
> We would also need to specify in the constructor the environment? So the device knows where it is and can call the environment methods.
> 
> Maybe also the environment needs to keep a reference of the devices in it? But that would probably lead to problems.

This is surely needed for lights, windows and rolling blinds. 

> Maybe also the environment needs to keep a reference of the devices in it? But that would probably lead to problems.

What's the advantage of traking the devices from enviroment's side?

**Comment by smagnaniuni** [comment]
> > Closes #19
> > @michelececcacci I am thinking of implementing another interface for a device whose location in the environment matters.
> > ```java
> > public interface EnvironmentObject {
> >   void move(Environment environment);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We would also need to specify in the constructor the environment? So the device knows where it is and can call the environment methods.
> > Maybe also the environment needs to keep a reference of the devices in it? But that would probably lead to problems.
> 
> This is surely needed for lights, windows and rolling blinds.

I am not sure what is the use for rolling blinds and also for lights (unless you want to track the illumination in the room, which is not in our required features atm).

> 
> > Maybe also the environment needs to keep a reference of the devices in it? But that would probably lead to problems.
> 
> What's the advantage of traking the devices from enviroment's side?

It depends on how we want to update the environmental parameters.
Each simulation tick, how do we update them? From the device side? From the environment itself? From a possibly `SimManager` which tracks both devices and environment?

**Comment by aleemont1** [comment]
> It depends on how we want to update the environmental parameters. Each simulation tick, how do we update them? From the device side? From the environment itself? From a possibly `SimManager` which tracks both devices and environment?

We'll have an endless loop, at every tick we'll get all data by polling all sensors/devices, send them to the controller who will "choose" what to do (activating new devices or changing their state eccetera). Creating a class to manage this "game loop" would probably make sense, but I have to think abt it. Let's hear from @michelececcacci 

Sensor's data might be updated in the controller.
E.G:
- The controller polls a temperature sensor and read the data.
- The controller generates a new value and send it to the sensor (can be done in another class, which will generate a coherent new value for temperature @michelececcacci we talked abt it)
And so on.

I don't understand what the problem is here.

**Comment by michelececcacci** [comment]
>We'll have an endless loop, at every tick we'll get all data by polling all sensors/devices, send them to the controller who will "choose" what to do (activating new devices or changing their state eccetera). Creating a class to manage this "game loop" would probably make sense, but I have to think abt it. Let's hear from @michelececcacci

i'm concerned about performance, but as a first implementation i think it's fine.

**Comment by smagnaniuni** [comment]
I think that was clear, but the doubt about the environment remains.

**Comment by smagnaniuni** [comment]
Since we want to be able to control time and maybe go like 10x or whatever, each parameter derivative (consumption, temperature difference, etc.) needs to be taken and multiplied for the time step.

**Comment by smagnaniuni** [comment]
> Since we want to be able to control time and maybe go like 10x or whatever, each parameter derivative (consumption, temperature difference, etc.) needs to be taken and multiplied for the time step.

This means different ways of doing it:
1. the device updates the environment parameters. This requires the device to have an updateTick(dt) method to know the time difference
2. the controller takes the values and knowing the time (since it would be called with an updateTick(dt) from the "game loop") it talks to the environment (not very high fidelity)
3. the environment is called with an updateTick(dt) and polls the devices, which means the environment keeping a list of the devices (I don't like this)

**Comment by michelececcacci** [comment]
LGTM

**Pull request merged**
