### PR TITLE
Implement Lights

### PR DESCRIPTION
**Pull request by aleemont1**
This PR implements a basic Light

### CODE REVIEW

**Review by smagnaniuni — APPROVED** [review]
lgtm

**Comment by aleemont1** [comment]
@michelececcacci Can I merge this, too?

**Comment by michelececcacci** [comment]
can you apply my suggestions, please?

**Comment by aleemont1** [comment]
> can you apply my suggestions, please?

I can't see them.

**Comment by michelececcacci** [comment]
They are literally above in this very pull request.

**Comment by aleemont1** [comment]
> They are literally above in this very pull request.

As I said, I can't see them.

image

**Comment by aleemont1** [comment]
@michelececcacci lmk.

**Pull request closed without merging**
