### PR TITLE
refactor AdjustableDevice

### PR DESCRIPTION
**Pull request by michelececcacci**

### CODE REVIEW

**Review by smagnaniuni — COMMENTED** [review]
lgtm
The outlet has a pending pull request

**Comment by aleemont1** [comment]
> lgtm
> The outlet has a pending pull request

Yep, how do we want to resolve this for not creating conflicts?

**Review by aleemont1 — APPROVED** [review]
Lgtm, we just need to decide how to manage the other PR on Outlet.

**Comment by michelececcacci** [comment]
> lgtm The outlet has a pending pull request

i'll take a look

**Comment by michelececcacci** [comment]
> Lgtm, we just need to decide how to manage the other PR on Outlet.

i'd say whoever merges last handles conflicts

**Comment by michelececcacci** [comment]
@smagnaniuni thoughts?

**Pull request merged**
